version: '3'

services:

  postgres:
    image: postgres:11-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data

  app:
    build:
      context: ./
      dockerfile: ./build/docker/Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    links:
      - "postgres:${APP_DB_HOST}"
    depends_on:
      - postgres
